### PR TITLE
use rabbit_registry to register exchange_decorator

### PR DESCRIPTION
**Pull request by hairyhum**
Related to https://github.com/rabbitmq/rabbitmq-server/pull/578
and https://github.com/rabbitmq/rabbitmq-common/pull/49

### CODE REVIEW

**Comment by michaelklishin** [comment]
`rabbit_exchange_decorator:register/2` does [more than simply call into `rabbit_registry`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_exchange_decorator.erl#L108). How will this be accounted for?

**Comment by hairyhum** [comment]
Yes. This logic is moved to `added_to(removed_from)_rabbit_registry` callback

**Comment by michaelklishin** [comment]
I have test failures:

```
dynamic_plugin_stop_start:         [running]
rabbit_federation_queue_test
----------------------------
rabbit_test_runner: make_test_single...simple:                            [running]*failed*
in function rabbit_federation_test_util:'-assert_link_status/3-fun-1-'/1 (test/src/rabbit_federation_test_util.erl, line 140)
in call from rabbit_federation_test_util:assert_link_status/3 (test/src/rabbit_federation_test_util.erl, line 140)
in call from lists:foldl/3 (lists.erl, line 1262)
in call from rabbit_federation_exchange_test:assert_connections/2 (test/src/rabbit_federation_exchange_test.erl, line 734)
in call from rabbit_federation_exchange_test:'-dynamic_plugin_stop_start_test/0-fun-0-'/2 (test/src/rabbit_federation_exchange_test.erl, line 591)
in call from rabbit_federation_exchange_test:with_ch/2 (test/src/rabbit_federation_exchange_test.erl, line 617)
in call from rabbit_test_runner:'-make_test_single/6-fun-0-'/5 (src/rabbit_test_runner.erl, line 108)
**error:{assertMatch,[{module,rabbit_federation_test_util},
              {line,140},
              {expression,"This"},
              {pattern,"[ _ ]"},
              {value,[]}]}
  output:<<"The following plugins have been disabled:
  rabbitmq_federation

Applying plugin configuration to rabbit@urano... stopped 1 plugin.
The following plugins have been enabled:
  rabbitmq_federation

Applying plugin configuration to rabbit@urano... started 1 plugin.
">>

 [PASSED].
multiple_upstreams:                [running] [PASSED].
multiple_downstreams:              [running] [PASSED].
bidirectional:                     [running] [PASSED].
dynamic_reconfiguration:           [running] [PASSED].
federate_unfederate:               [running] [PASSED].
dynamic_plugin_stop_start:         [running] [PASSED].
upstream_has_no_federation:        [running] [PASSED].

rabbit_federation_unit_test
---------------------------
serialisation:                     [running] [PASSED].
scratch_space:                     [running] [PASSED].
remove_credentials:                [running] [PASSED].
=======================================================
  Failed: 1.  Skipped: 0.  Passed: 23.


rabbit_test_runner:run_in_broker("/Users/antares/Development/RabbitMQ/umbrella.git/deps/rabbitmq_federation/test","all").
{ok, error}

FAILED
```

**Comment by hairyhum** [comment]
I cannot reproduce following failure. Did you updated rabbit_common, rabbitmq-server and rabbitmq-test repos?

**Comment by michaelklishin** [comment]
@hairyhum most certainly I had `rabbitmq-server-559` checked out in those repos.

**Pull request merged**
